//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet.Models.Actions
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramInter
    {
        public int idProgramare { get; set; }
        public int idInterventie { get; set; }
    
        public virtual Programare Programare { get; set; }
    }
}
