//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet.Models.Actions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programare()
        {
            this.ProgramInter = new HashSet<ProgramInter>();
        }
    
        public int idProgramare { get; set; }
        public int idPacient { get; set; }
        public Nullable<System.DateTime> dataProgramare { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Pacient Pacient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramInter> ProgramInter { get; set; }
    }
}
