//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programare
    {
        public int idProgramare { get; set; }
        public int idPacient { get; set; }
        public Nullable<System.DateTime> dataProgramare { get; set; }
        public bool isDeleted { get; set; }
        public int ProgramInter_idProgramare { get; set; }
        public int ProgramInter_idInterventie { get; set; }
    
        public virtual Pacient Pacient { get; set; }
        public virtual ProgramInter ProgramInter { get; set; }
    }
}
